# Setup
#theme: jekyll-theme-cayman
remote_theme: pietromenna/jekyll-cayman-theme

title:        Wice.js
tagline:      WICE, acronym for Web Interactive Canvas Exercises, is a library to create interactive exercises using HTML Canvas.
description:  WICE, acronym for Web Interactive Canvas Exercises, is a library to create interactive exercises using HTML Canvas.
baseurl:      ""
paginate:     1
locale:       "en"
show_downloads: true

# About/contact
author:
  name:       Yulio Aleman Jimenez
  url:        https://github.com/yulioaj290

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
