source 'https://rubygems.org'
# source 'http://nexus.prod.uci.cu/repository/rubygems-proxy/'

#gemspec

gem 'jekyll'
gem 'jekyll-paginate'
gem 'pygments.rb'
gem 'github-pages', group: :jekyll_plugins
gem 'jekyll-theme-cayman'
gem 'kramdown', '>= 2.3.0'
gem 'nokogiri', '>= 1.10.8'